version: '3'
services:
  s3:
    image: minio/minio:RELEASE.2019-06-01T03-46-14Z
    command: ["server", "/data"]
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: 'xxx'
      MINIO_SECRET_KEY: 'xxxxxxxx'
      MINIO_HTTP_TRACE: '/dev/stdout'
      MINIO_REGION: 'minio-test-region'
  sqs:
    image: softwaremill/elasticmq:0.14.10
    ports:
      - 9324:9324
    command: ["-Dorg.slf4j.simpleLogger.logFile=System.out"]
