variables:
  GIT_SUBMODULE_STRATEGY: recursive

format-cpp:
  stage: build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  script:
    - cd backend/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make check-format

format-python:
  stage: build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  before_script:
    - pip3 install -r requirements.txt
    - pip3 install -r python/jitq/benchmarks/requirements.txt
    - pip3 install -r python/jitq/tests/requirements.txt
  script:
    - tools/check_format_python.sh
    - tools/check_pylint.sh

rel-build:
  stage: build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  script:
    - cd backend/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make
  artifacts:
    paths:
      - backend/build/*

dbg-build:
  stage: build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  script:
    - cd backend/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - make
  artifacts:
    paths:
      - backend/build/*

clang-tidy:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  script:
    - cd backend/build
    - make -k check-tidy

cppcheck:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  script:
    - cd backend/build
    - make cppcheck

python-tests:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  variables:
    JITQPATH: $CI_PROJECT_DIR
    LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/clang+llvm-5.0.0/lib
    PYTHONPATH: $CI_PROJECT_DIR
    OMP_NUM_THREADS: 8
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev
    - pip3 install -r requirements.txt
    - pip3 install -r python/jitq/tests/requirements.txt
    - echo -e "CC=clang-5.0\nCXX=clang++-5.0" > backend/src/code_gen/cpp/Makefile.local
    - cp jitq_config.ci.json jitq_config.json
  script:
    - cd python
    - catchsegv python3 -m unittest discover -v -s jitq/tests

cpp-test:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2018-08-02
  variables:
    GTEST_COLOR: "1"
  script:
    - cd backend/build
    - ctest -V
