variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIO_ACCESS_KEY: 'xxx'
  MINIO_SECRET_KEY: 'xxxxxxxx'
  MINIO_HTTP_TRACE: '/dev/stdout'
  AWS_ACCESS_KEY_ID: 'xxx'
  AWS_SECRET_ACCESS_KEY: 'xxxxxxxx'
  AWS_S3_ENDPOINT: 'http://s3server:9000'
  PYTEST_ADDOPTS: '--color=yes -vs'
  GTEST_COLOR: "1"
  PYTHONPATH: $CI_PROJECT_DIR:$CI_PROJECT_DIR/backend/build
  JITQPATH: $CI_PROJECT_DIR
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/clang+llvm-7.0.1/lib
  ASAN_SYMBOLIZER_PATH: /opt/clang+llvm-7.0.1/bin/llvm-symbolizer
  ASAN_LIBRARY_PATH: /opt/clang+llvm-7.0.1/lib/clang/7.0.1/lib/linux/libclang_rt.asan-x86_64.so
  SEGFAULT_SIGNALS: "bus abrt"
  CC: clang-7.0
  CXX: clang++-7.0

services:
  - name: minio/minio:RELEASE.2019-06-01T03-46-14Z
    command: ["server", "/data"]
    alias: s3server

format-cpp:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  script:
    - cd backend/build
    - cmake ../src
    - make check-format

format-python:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  before_script:
    - pip3 install -r requirements.txt
  script:
    - tools/check_format_python.sh
    - tools/check_pylint.sh

rel-build:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  script:
    - cd backend/build
    - cmake ../src
    - make
  artifacts:
    paths:
      - backend/build/*

dbg-build:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  variables:
    ASAN_OPTIONS: detect_leaks=0
  script:
    - cd backend/build
    - >-
        cmake ../src
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DLLVM_ASAN=ON
    - make
  artifacts:
    paths:
      - backend/build/*

clang-tidy:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  script:
    - cd backend/build
    - make -k check-tidy

cppcheck:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  script:
    - cd backend/build
    - make cppcheck

python-tests-parallel:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  tags:
    - ptrace
  variables:
    OMP_NUM_THREADS: 8
    # Deactivate LSan, as somehow it doesn't work inside docker and with several OpenMP threads
    ASAN_OPTIONS: detect_leaks=0
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev time
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-7.0\nCXX=clang++-7.0\nLIBOMPDIR=/opt/clang+llvm-7.0.1/lib" > backend/src/generate/src/code_gen/Makefile.local
    - cp jitq_config.ci.json jitq_config.json
  script:
    - cd python/jitq/tests
    - /usr/bin/time -v catchsegv $JITQPATH/tools/run_with_asan.sh python3 -u -m pytest test_parallel_enironment.py --parallelize true
    - /usr/bin/time -v catchsegv $JITQPATH/tools/run_with_asan.sh python3 -u -m pytest test_operators.py --parallelize true

python-tests-asan:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  tags:
    - ptrace
  variables:
    OMP_NUM_THREADS: 1
    ASAN_OPTIONS: detect_leaks=1
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev graphviz time
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-7.0\nCXX=clang++-7.0\nLIBOMPDIR=/opt/clang+llvm-7.0.1/lib" > backend/src/generate/src/code_gen/Makefile.local
    - cp jitq_config.ci.json jitq_config.json
  script:
    - cd python/jitq/tests
    - /usr/bin/time -v catchsegv $JITQPATH/tools/run_with_asan.sh python3 -u -m pytest

cpp-test:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-08-12
  tags:
    - ptrace
  before_script:
    - apt-get update && apt-get install -y time
  variables:
    # Unlike the test executables are compiled with ASAN, so no need to pre-load
    ASAN_LIBRARY_PATH: ""
  script:
    - cd backend/build
    - /usr/bin/time -v catchsegv ../../tools/run_with_asan.sh ctest -V
