variables:
  GIT_SUBMODULE_STRATEGY: recursive

format-cpp:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  script:
    - cd backend/build
    - >-
        CC=clang-7.0 CXX=clang++-7.0
        cmake ../src
        -DLLVM_DIR=/opt/clang+llvm-7.0.1/lib/cmake/llvm/
        -Darrow_DIR=/opt/arrow-0.14/lib/cmake/arrow
    - make check-format

format-python:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  variables:
    PYTHONPATH: $CI_PROJECT_DIR:$CI_PROJECT_DIR/backend/build
  before_script:
    - pip3 install -r requirements.txt
  script:
    - tools/check_format_python.sh
    - tools/check_pylint.sh

rel-build:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  script:
    - cd backend/build
    - >-
        CC=clang-7.0 CXX=clang++-7.0
        cmake ../src
        -DLLVM_DIR=/opt/clang+llvm-7.0.1/lib/cmake/llvm/
        -Darrow_DIR=/opt/arrow-0.14/lib/cmake/arrow
    - make
  artifacts:
    paths:
      - backend/build/*

dbg-build:
  stage: build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  variables:
    ASAN_OPTIONS: detect_leaks=0
  script:
    - cd backend/build
    - >-
        CC=clang-7.0 CXX=clang++-7.0
        cmake ../src
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DLLVM_ASAN=ON
        -DLLVM_DIR=/opt/clang+llvm-7.0.1/lib/cmake/llvm/
        -Darrow_DIR=/opt/arrow-0.14/lib/cmake/arrow
    - make
  artifacts:
    paths:
      - backend/build/*

clang-tidy:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  script:
    - cd backend/build
    - make -k check-tidy

cppcheck:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  script:
    - cd backend/build
    - make cppcheck

python-tests-parallel:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  tags:
    - ptrace
  variables:
    JITQPATH: $CI_PROJECT_DIR
    LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/clang+llvm-7.0.1/lib
    PYTHONPATH: $CI_PROJECT_DIR/python:$CI_PROJECT_DIR/backend/build
    OMP_NUM_THREADS: 8
    ASAN_SYMBOLIZER_PATH: /opt/clang+llvm-7.0.1/bin/llvm-symbolizer
    ASAN_LIBRARY_PATH: /opt/clang+llvm-7.0.1/lib/clang/7.0.1/lib/linux/libclang_rt.asan-x86_64.so
    # Deactivate LSan, as somehow it doesn't work inside docker and with several OpenMP threads
    ASAN_OPTIONS: detect_leaks=0
    SEGFAULT_SIGNALS: "bus abrt"
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev time
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-7.0\nCXX=clang++-7.0\nLIBOMPDIR=/opt/clang+llvm-7.0.1/lib" > backend/src/code_gen/cpp/Makefile.local
    - cp jitq_config.ci.json jitq_config.json
  script:
    - /usr/bin/time -v catchsegv tools/run_with_asan.sh python3 -u python/jitq/tests/test_cpp_backend_parallel.py -v

python-tests-asan:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  tags:
    - ptrace
  variables:
    JITQPATH: $CI_PROJECT_DIR
    LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/clang+llvm-7.0.1/lib
    PYTHONPATH: $CI_PROJECT_DIR/python:$CI_PROJECT_DIR/backend/build
    OMP_NUM_THREADS: 1
    ASAN_SYMBOLIZER_PATH: /opt/clang+llvm-7.0.1/bin/llvm-symbolizer
    ASAN_LIBRARY_PATH: /opt/clang+llvm-7.0.1/lib/clang/7.0.1/lib/linux/libclang_rt.asan-x86_64.so
    ASAN_OPTIONS: detect_leaks=1
    SEGFAULT_SIGNALS: "bus abrt"
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev time
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-7.0\nCXX=clang++-7.0\nLIBOMPDIR=/opt/clang+llvm-7.0.1/lib" > backend/src/code_gen/cpp/Makefile.local
    - cp jitq_config.ci.json jitq_config.json
  script:
    - cd python
    - /usr/bin/time -v catchsegv ../tools/run_with_asan.sh python3 -u -m unittest discover -v -s jitq/tests

cpp-test:
  stage: test
  dependencies:
    - dbg-build
  image: ingomuellernet/buildenv-jitq:2019-07-21
  tags:
    - ptrace
  variables:
    GTEST_COLOR: "1"
    SEGFAULT_SIGNALS: "bus abrt"
  before_script:
    - apt-get update && apt-get install -y time
  script:
    - cd backend/build
    - /usr/bin/time -v catchsegv ../../tools/run_with_asan.sh ctest -V
