variables:
  GIT_SUBMODULE_STRATEGY: recursive

format-cpp:
  stage: build
  image: ingomuellernet/buildenv-jitq
  script:
    - cd backend/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make check-format

format-python:
  stage: build
  image: ingomuellernet/buildenv-jitq
  before_script:
    - pip3 install -r requirements.txt
    - pip3 install -r python/jitq/benchmarks/requirements.txt
  script:
    - tools/check_format_python.sh
    - tools/check_pylint.sh

build:
  stage: build
  image: ingomuellernet/buildenv-jitq
  script:
    - cd backend/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make
  artifacts:
    paths:
      - backend/build/*

clang-tidy:
  stage: build
  image: ingomuellernet/buildenv-jitq
  script:
    - cd backend/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/ -DCMAKE_CXX_CLANG_TIDY:STRING="clang-tidy-5.0;-extra-arg=-I/opt/clang+llvm-5.0.0/lib/clang/5.0.0;-header-filter=/builds/OU-SYSTEMS/jitq/backend/src/"
    - make

cppcheck:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv-jitq
  script:
    - cd backend/build
    - make cppcheck

python-tests:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv-jitq
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
    JITQPATH: $CI_PROJECT_DIR
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-5.0\nCXX=clang++-5.0" > backend/src/code_gen/cpp/Makefile.local
  script:
    - cd python
    - python3 -m unittest discover -v -s jitq/tests

cpp-test:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv-jitq
  script:
    - cd backend/build
    - ctest -V
