variables:
  GIT_SUBMODULE_STRATEGY: recursive

format:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - apt-get update && apt-get install -y libgraphviz-dev libboost-dev
  script:
    - cd cpp/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make check-format

build:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - apt-get update && apt-get install -y libgraphviz-dev libboost-dev
  script:
    - cd cpp/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make
  artifacts:
    paths:
      - cpp/build/*

clang-tidy:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - apt-get update && apt-get install -y libgraphviz-dev libboost-dev
  script:
    - cd cpp/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/ -DCMAKE_CXX_CLANG_TIDY:STRING="clang-tidy-5.0;-extra-arg=-I/opt/clang+llvm-5.0.0/lib/clang/5.0.0;-header-filter=/builds/OU-SYSTEMS/msc-sakhadov/cpp/src/"
    - make

cppcheck:
  stage: test
  dependencies:
    - build
  before_script:
    - apt-get update && apt-get install -y libgraphviz-dev libboost-dev
  image: ingomuellernet/buildenv
  script:
    - cd cpp/build
    - make cppcheck

python-tests:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
    BLAZEPATH: $CI_PROJECT_DIR
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-5.0\nCXX=clang++-5.0" > cpp/src/operators/Makefile.local
  script:
    - cd blaze/tests
    - python3 -m unittest discover -v

cpp-test:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv
  script:
    - cd cpp/build
    - ctest -V
