variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIO_ACCESS_KEY: 'xxx'
  MINIO_SECRET_KEY: 'xxxxxxxx'
  MINIO_HTTP_TRACE: '/dev/stdout'
  MINIO_REGION: 'minio-test-region'
  AWS_ACCESS_KEY_ID: 'xxx'
  AWS_SECRET_ACCESS_KEY: 'xxxxxxxx'
  AWS_DEFAULT_REGION: 'minio-test-region'
  AWS_LAMBDA_ENDPOINT: 'http://doesnotwork.local:1234'  # Not used in CI tests but must exist
  AWS_S3_ENDPOINT: 'http://s3server.local:9000'
  AWS_SQS_ENDPOINT: 'http://sqsserver.local:9324'
  PYTEST_ADDOPTS: >-
      --color=yes -vs
      --log-cli-level INFO
      --log-format="%(asctime)s.%(msecs)03d  %(levelname)-8s %(module)s:%(funcName)s:%(lineno)-5d   %(message)s"
  PYTEST_ASAN_CMD: /usr/bin/time -v catchsegv $CI_PROJECT_DIR/tools/run_with_asan.sh python3 -u -m pytest
  GTEST_COLOR: "1"
  PYTHONPATH: $CI_PROJECT_DIR/python:$CI_PROJECT_DIR/backend/build
  JITQPATH: $CI_PROJECT_DIR
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/clang+llvm-9.0.0/lib
  ASAN_SYMBOLIZER_PATH: /opt/clang+llvm-9.0.0/bin/llvm-symbolizer
  ASAN_LIBRARY_PATH: /opt/clang+llvm-9.0.0/lib/clang/9.0.0/lib/linux/libclang_rt.asan-x86_64.so
  ASAN_OPTIONS: intercept_tls_get_addr=0
  SEGFAULT_SIGNALS: "bus abrt"
  CC: clang-9.0
  CXX: clang++-9.0

services:
  - name: minio/minio:RELEASE.2019-06-01T03-46-14Z
    command: ["server", "/data"]
    alias: s3server.local
  - name: softwaremill/elasticmq:0.14.10
    command: ["-Dorg.slf4j.simpleLogger.logFile=System.out"]
    alias: sqsserver.local

default:
  image: ingomuellernet/buildenv-jitq:2020-11-13
  before_script:
    - pip3 install -r requirements.txt
    - >-
        echo -e
        "CC=clang-9.0\nCXX=clang++-9.0\nCXXFORMAT=clang-format-9.0\nLIBOMPDIR=/opt/clang+llvm-9.0.0/lib"
        > backend/src/generate/src/code_gen/Makefile.local
    - cp jitq_config.ci.json jitq_config.json
  after_script:
    - $JITQPATH/tools/create_coverage_summary.sh coverage.$CI_JOB_NAME.json

format-cpp:
  stage: build
  script:
    - cd backend/build
    - cmake ../src
    - make check-format

format-python:
  stage: build
  script:
    - tools/check_format_python.sh
    - tools/check_pylint.sh

rel-build:
  stage: build
  script:
    - cd backend/build
    - cmake ../src
    - make
  artifacts:
    paths:
      - backend/build/*
    exclude:
      - backend/build/**/*.o

dbg-build:
  stage: build
  variables:
    # Deactivate LSan here to avoid needing ptrace
    ASAN_OPTIONS: detect_leaks=0
  script:
    - cd backend/build
    - >-
        cmake ../src
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DWITH_LLVM_ASAN=ON
        $(if [[ $CI_COMMIT_BRANCH == *'-coverage' || $CI_COMMIT_BRANCH == 'master' ]]; then echo -n -DWITH_LLVM_COVERAGE=ON; fi)
    - make
  artifacts:
    paths:
      - backend/build/*
    exclude:
      - backend/build/**/*.o

clang-tidy:
  stage: test
  dependencies:
    - dbg-build
  script:
    - cd backend/build
    - make -k check-tidy

cppcheck:
  stage: test
  dependencies:
    - dbg-build
  script:
    - cd backend/build
    - make cppcheck

inlining-test:
  stage: test
  dependencies:
    - rel-build
  tags:
    - ptrace
  script:
    - cd python/jitq/tests
    - $PYTEST_ASAN_CMD test_inlining.py

python-tests-omp:
  stage: test
  dependencies:
    - dbg-build
  tags:
    - ptrace
  variables:
    OMP_NUM_THREADS: 8
  script:
    - cd python/jitq/tests
    - $PYTEST_ASAN_CMD test_omp_environment.py --target omp
    - $PYTEST_ASAN_CMD test_operators.py --target omp
  artifacts:
    paths:
      - "coverage.*.json"

.tests-asan:
  stage: test
  dependencies:
    - dbg-build
  tags:
    - ptrace
  artifacts:
    paths:
      - "coverage.*.json"

python-tests-asan:
  extends: .tests-asan
  script:
    - cd python/jitq/tests
    - $PYTEST_ASAN_CMD test_cli_runner.py
    - $PYTEST_ASAN_CMD test_lambda_runner.py --target singlecore

operator-tests-asan:
  extends: .tests-asan
  script:
    - cd python/jitq/tests
    - $PYTEST_ASAN_CMD test_operators.py

optimizer-tests-asan:
  extends: .tests-asan
  script:
    - cd python/jitq/tests
    - $PYTEST_ASAN_CMD test_optimizer.py

tpch-tests-asan:
  extends: .tests-asan
  script:
    - cd python/jitq/tests
    - $PYTEST_ASAN_CMD test_tpch.py --target singlecore
    - $PYTEST_ASAN_CMD test_tpch.py --target singlecore --tpch_input_format parquet
    - $PYTEST_ASAN_CMD test_tpch.py --target process    --tpch_input_format parquet
    - $PYTEST_ASAN_CMD test_tpch.py --target lambda     --tpch_input_format parquet

cpp-test:
  stage: test
  dependencies:
    - dbg-build
  tags:
    - ptrace
  variables:
    # Unlike the python tests, these test executables are compiled with ASAN, so no need to pre-load
    ASAN_LIBRARY_PATH: ""
  script:
    - cd backend/build
    - /usr/bin/time -v catchsegv ../../tools/run_with_asan.sh ctest -V
  artifacts:
    paths:
      - "coverage.*.json"

code-coverage:
  stage: deploy
  only:
    - /.*-coverage/
    - master
  dependencies:
    - cpp-test
    - python-tests-asan
    - python-tests-omp
    - operator-tests-asan
    - optimizer-tests-asan
    - tpch-tests-asan
  script:
    - $JITQPATH/tools/create_coverage_report.sh $JITQPATH/coverage.*.json
  artifacts:
    paths:
      - coverage*
    reports:
      cobertura:
        - coverage/coverage.xml
