variables:
  GIT_SUBMODULE_STRATEGY: recursive

format:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - apt-get update && apt-get install -y libgraphviz-dev
  script:
    - cd cpp/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make check-format

build:
  stage: build
  image: ingomuellernet/buildenv
  before_script:
    - apt-get update && apt-get install -y libgraphviz-dev
  script:
    - cd cpp/build
    - CC=clang-5.0 CXX=clang++-5.0 cmake-3.10 ../src -DLLVM_DIR=/opt/clang+llvm-5.0.0/lib/cmake/llvm/
    - make
  artifacts:
    paths:
      - cpp/build/*

operator-test:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
    BLAZEPATH: $CI_PROJECT_DIR
  before_script:
    - apt-get update && apt-get install -y python3-pip libgraphviz-dev
    - pip3 install -r requirements.txt
    - echo -e "CC=clang-5.0\nCXX=clang++-5.0" > cpp/src/operators/Makefile.local
  script:
    - blaze/tests/test_operators.py -q

cpp-test:
  stage: test
  dependencies:
    - build
  image: ingomuellernet/buildenv
  script:
    - cd cpp/build
    - ctest -V
